---
title: "EDS 221 Day 3 Comp"
author: "Michelle Lam"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(palmerpenguins)
```

### `if` statements

```{r}
burrito <- 4

if (burrito > 2) {
  print("I love burritos!")
}
```

```{r}
my_ships <- c("Millenium Falcom", "X-wing", "Tie-Fighter", "Death Star")

# Check to see which elements in the my_ships vector contain an "r"
# Capitalization does matter when specifying the pattern
str_detect(my_ships, pattern = "r")
str_detect(my_ships, pattern = "x")

phrase <- "I love burritos"

if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}
```


### `if-else` statement

```{r}
pika <- 50

if (pika > 60) {
  print("mega pika")
} else {
  print("normal pika")
}
```

```{r}
marmot <- 2.8

if(marmot < 0.5) {
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print("this is a large marmot")
}
```

#### `group_by() %>% summarize()`

```{r}
penguins |> 
  group_by(species, island) |> 
  summarize(mean_bill_length = mean(bill_length_mm, na.rm = TRUE), 
            sd_bill_length =sd(bill_length_mm, na.rm = TRUE),
            n = n())

# Start by looking at penguins data, find the groups by species and the subgroup of each island, find the mean of each group and the standard deviation 
# n = how many penguins observed, does not remove the na values from the count

# Find the mean and standard deviation of character height in `starwars` grouped by homeworld.

starwars |> 
  group_by(homeworld) |> 
  summarize(mean_character_height = mean(height, na.rm = TRUE),
            sd_character_height = sd(height, na.rm = TRUE))

# Find the maximum and minimum flipper length, and sample size for each species of penguins 
penguins |> 
  group_by(species, sex) |> 
  summarize(max_flipper_length = max(flipper_length_mm, na.rm = TRUE),
            min_flipper_length = min(flipper_length_mm, na.rm = TRUE),
            n = n())

# Use `group_by() %>% summarize()` with `across()` to filter for columns containing numeric values
penguins |> 
  group_by(species) |> 
  summarize(across(where(is.numeric), mean, na.rm = TRUE))
```

#### For Loops
```{r}
# Create vector where the next value in the vector is added to it
tree_height <- c(1, 2, 6, 10, 14, 20)

for (i in seq_along(tree_height)) {
  val = tree_height[i] + tree_height[i + 1]
  print(val)
}
```

### For loops with conditional statement
```{r}
# Create empty vector to populate calculated animal_age of each iteration into 
animal_ages <- vector(mode = "numeric", length = length(species))

species <- c("dog", "elephant", "goat", "dog", "dog", "elephant")

age_human <- c(3, 8, 4, 6, 12, 18)

for (i in seq_along(species)) {
  if (species[i] == "dog") {
    animal_age <- age_human[i] * 7
  } else if (species[i] == "elephant") {
    animal_age <- age_human[i] * 0.88
  } else if (species[i] == "goat") {
    animal_age <- age_human[i] * 4.7
  }
  animal_ages[i] <- animal_age
}
```

### For loops across data frames
```{r}
mean_mtcars <- vector(mode = "numeric", length = ncol(mtcars))

for (i in seq_along(mtcars)) {
  mean_val <- mean(mtcars[[i]], na.rm = TRUE)
  mean_mtcars[i] <- mean_val
}

mean_mtcars
```

### Functional programming examples

Adding syntactic sugar (apply, across, map_df)

```{r}
# find the mean across all columns of mtcars using apply
apply(X = mtcars, MARGIN = 2, FUN = mean)
```

```{r}
# find the mean across all columns of mtcars using map
map(.x = mtcars, .f = mean)

# map_df returns the data as a data frame
map_df(.x = mtcars, .f = mean)
```

#### Example of %in% operator

```{r}
# |> and %>% do the same thing. The |> is the native pipe function that can be used outside the tidyverse package.

tatooine_characters <- starwars |> 
  filter(homeworld == "Tatooine")

# Use %in% operator to check for multiple positive matches. Shorthand to for OR operator (|)
tatooine_endor_naboo <- starwars |> 
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))

# In words: Does the value in the homeworld variable for that row exist IN that vector c("Tatooine", "Naboo", "Endor")

unique(starwars$eye_color)
# returns the unique values in the eye_color column of the star wars data set. If values are green and green-gray it will return 2 unique values.
```



